[tool.poetry]
name = "supplier-etl"
version = "0.1.0"
description = "Collection of services for supplier etl"
authors = ["Miles Bloom <miles@prolo.io>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.3.2"
ipykernel = "^6.30.1"